# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Publish

on: workflow_dispatch

jobs:
  publish:
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout main branch & Change path to client 
      uses: actions/checkout@v2
      with: 
        ref: 'main'
    - name: Set Java Env
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD

    - name: Build with Maven
      run: mvn -B package -Dmaven.test.skip=true --file java/baiduads-sdk-package-maven-plugin/pom.xml

    - name: Release Maven package
      uses: samuelmeuli/action-maven-publish@v1
      with:
        gpg_private_key: ${{ secrets.GPG_SECRET }}
        gpg_passphrase: ${{ secrets.GPG_PASSWD }}
        nexus_username: ${{ secrets.OSSRH_USER }}
        nexus_password: ${{ secrets.OSSRH_PASSWD }}
        directory: java/baiduads-sdk-package-maven-plugin/
        maven_args: -Dmaven.test.skip=true -Dgpg.skip=false
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USER }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWD }}
